### ISSUE TITLE
Quasar with unocss and storybook

### ISSUE THREAD

**Issue by oefeningen** [tasynguyen3894/demo_quasar_storybook_i18n_pinia#1]
I'm using quasar with unocss.  I followed your instructions and everything related to quasar worked,  but i didn't get unocss running in storybook.  
Do you have any thought on how to implement that?

**Comment by tasynguyen3894** [comment]
hi @oefeningen , thanks you for your issue. Honestly, I never tried unocss before. But I've tried to install it in this project this morning. So I think I will try to implement that tonight.

**Comment by oefeningen** [comment]
That would be great!  Thank you very much!

**Comment by tasynguyen3894** [comment]
Hi, I made an example with the UnoCSS in the branch "feat/example_with_unocss". To do it, we just follow the same way with the alias and Quasar style. Firstly, we need to install the UnoCSS plugin in the ".storybook/main.ts" like this:

```ts
import UnoCSS from 'unocss/vite';

async viteFinal(config) {
  if(config.resolve) {
    config.resolve.alias  = {
      ...config.resolve.alias,
      'src': path.resolve(__dirname, "../src"),
    };
  }
  if(config.plugins) {
    config.plugins.push(UnoCSS());
  }
  return config;
},
```

Then, we just need to import the CSS from UnoCSS in the ".storybook/preview.ts" like this:

```ts
import 'uno.css';
```

**Comment by oefeningen** [comment]
Great!  This will be very usefull to me!  Thank you!
